services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  # for SSL certs
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mern-net
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - compiler-service
    restart: unless-stopped
    networks:
      - mern-net

  compiler-service:
    build:
      context: ./compiler-service
      dockerfile: Dockerfile
    container_name: compiler-service
    env_file:
      - ./compiler-service/.env
    restart: unless-stopped
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge
